feat(FEC-10783): create BP plugin
kaltura/playkit-js-broadpeak-smartlib pull request #1
Opened 2020-12-22 14:40 UTC by Yuvalke

enable to use of broadpeak smartlib as a plugin which replacing our source by source we're getting from broadpeak smartlib.

2021-01-17 14:38 UTC, Yuvalke commented on src/bp-engine-decorator.js
> +class BpEngineDecorator implements IEngineDecorator {
Kept it with BP instead of BroadPeak

2021-01-18 07:55 UTC, dan-ziv requested changes
@Yuvalke LGTM but need to update README to integration with kaltura player and not playkit (see here https://github.com/kaltura/playkit-js-airplay)

2021-01-18 08:00 UTC, dan-ziv commented on src/bp-engine-decorator.js
> +class BpEngineDecorator implements IEngineDecorator {
It's your call, but naming usually should be consistent and not change from file to file.

2021-01-18 08:04 UTC, Yuvalke commented on src/bp-engine-decorator.js
> +class BpEngineDecorator implements IEngineDecorator {
It's, also middleware use the shortcut and once it was broadpeak smartlib it also used BP instead broadpeak

2021-01-18 08:07 UTC, dan-ziv commented on README.md
> +The plugin requires [Kaltura Player JS] to be loaded first.
Title link is broken. need to add
[kaltura player js]: https://github.com/kaltura/kaltura-player-js

2021-01-18 08:21 UTC, dan-ziv approved these changes

2021-01-18 08:22 UTC, merged